
from enum import IntEnum

APP_WIDTH = 128
APP_HEIGHT = 128
BORDER_WIDTH = 4

COLLIDE_RIGHT = APP_WIDTH - BORDER_WIDTH
COLLIDE_LEFT = BORDER_WIDTH
COLLIDE_BOTTOM = APP_HEIGHT - (BORDER_WIDTH * 2)
COLLIDE_TOP = BORDER_WIDTH

class BubbleType(IntEnum):
   TINY = 1
   SMALL = 2
   MEDIUM = 3
   LARGE = 4

MAX_SCORE = 999999
SCORE_BUBBLES = {
   BubbleType.TINY : 200,
   BubbleType.SMALL : 150,
   BubbleType.MEDIUM : 100,
   BubbleType.LARGE : 50,
}
SCORE_SEC_REMAINING_BONUS = 100

MAX_STAGE_NUMBER = 9

MUSIC_CHANNEL_0 = 0
MUSIC_CHANNEL_1 = 1
SOUND_CHANNEL = 3
#
MUS_GAMEPLAY = 0
#
SND_POP = 60
SND_SHOOT = 61
SND_DIED = 62
#
SND_STAGE_CLEAR = 63